<?php

namespace AppBundle\Repository;

/**
 * RouteStopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RouteStopRepository extends \Doctrine\ORM\EntityRepository
{
}
